[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "frontend/.next"

[build.environment]
  NODE_VERSION = "22.14.0"
  API_PROXY_TARGET = "https://naveen710-swing-api.onrender.com/api"
